# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: esteroides.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'esteroides.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65steroides.proto\x12\nesteroides\"\x07\n\x05Vazio\"M\n\tEsteroide\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x02\x12\x11\n\tcategoria\x18\x03 \x01(\t\x12\x10\n\x08\x65m_stock\x18\x04 \x01(\x08\"<\n\x0fListaEsteroides\x12)\n\nesteroides\x18\x01 \x03(\x0b\x32\x15.esteroides.Esteroide\"$\n\x10RespostaMensagem\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\xa2\x01\n\x11\x45steroidesService\x12\x42\n\x10ListarEsteroides\x12\x11.esteroides.Vazio\x1a\x1b.esteroides.ListaEsteroides\x12I\n\x12\x41\x64icionarEsteroide\x12\x15.esteroides.Esteroide\x1a\x1c.esteroides.RespostaMensagemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'esteroides_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VAZIO']._serialized_start=32
  _globals['_VAZIO']._serialized_end=39
  _globals['_ESTEROIDE']._serialized_start=41
  _globals['_ESTEROIDE']._serialized_end=118
  _globals['_LISTAESTEROIDES']._serialized_start=120
  _globals['_LISTAESTEROIDES']._serialized_end=180
  _globals['_RESPOSTAMENSAGEM']._serialized_start=182
  _globals['_RESPOSTAMENSAGEM']._serialized_end=218
  _globals['_ESTEROIDESSERVICE']._serialized_start=221
  _globals['_ESTEROIDESSERVICE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
