# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import esteroides_pb2 as esteroides__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in esteroides_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EsteroidesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarEsteroides = channel.unary_unary(
                '/esteroides.EsteroidesService/ListarEsteroides',
                request_serializer=esteroides__pb2.Vazio.SerializeToString,
                response_deserializer=esteroides__pb2.ListaEsteroides.FromString,
                _registered_method=True)
        self.AdicionarEsteroide = channel.unary_unary(
                '/esteroides.EsteroidesService/AdicionarEsteroide',
                request_serializer=esteroides__pb2.Esteroide.SerializeToString,
                response_deserializer=esteroides__pb2.RespostaMensagem.FromString,
                _registered_method=True)


class EsteroidesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarEsteroides(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdicionarEsteroide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EsteroidesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarEsteroides': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarEsteroides,
                    request_deserializer=esteroides__pb2.Vazio.FromString,
                    response_serializer=esteroides__pb2.ListaEsteroides.SerializeToString,
            ),
            'AdicionarEsteroide': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarEsteroide,
                    request_deserializer=esteroides__pb2.Esteroide.FromString,
                    response_serializer=esteroides__pb2.RespostaMensagem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'esteroides.EsteroidesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('esteroides.EsteroidesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EsteroidesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarEsteroides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esteroides.EsteroidesService/ListarEsteroides',
            esteroides__pb2.Vazio.SerializeToString,
            esteroides__pb2.ListaEsteroides.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdicionarEsteroide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/esteroides.EsteroidesService/AdicionarEsteroide',
            esteroides__pb2.Esteroide.SerializeToString,
            esteroides__pb2.RespostaMensagem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
